version: '3'
services:
  node-comp-app:
    container_name: node-comp
    image: mohamedmoniem/tresmerge-docker
    ports:
      - "4000:4000"  
    env_file:
      - ./.env
    depends_on:
      # - postgres 
      - mongo

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db #to save data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  #     ME_CONFIG_BASICAUTH: false

  #   depends_on:
  #     - mongo
    

  redis:
    image: redis 

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.config:/etc/nginx/conf.d/default/conf

    depends_on: 
      - node-comp-app


  # postgres:
  #   image: postgres
  #   restart: always
  #   volumes:
  #     # - postgres-db:/var/lib/postgresql/data #to save data
  #      - "./pgdata:/var/lib/postgresql/data/pgdata"
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: example




       

  
volumes:
   mongo-db: